I'd be talking about the 5 most common type of encodings:
* Label Encoding
* Ordinal Encoding
* Frequency Encoding
* One Hot Encoding
* Binary Encoding

Given a dataset below:

In [113]:
import pandas as pd
import numpy as np
df = {'Temp':['Hot','Cold','Warm','Very Cold','Hot','Cold','Very Hot','Hot','Warm','Hot'],
      'Color':['Red','Blue','Yellow','Yellow','Blue','Red','Blue','Blue','Yellow','Red'],'Target':[1,1,1,0,0,1,0,0,1,0]}
df = pd.DataFrame(df)

LABEL ENCODING

Label encoding is used to encode ordinal categorical variables i.e. variables that can be ordered e.g. size of a shirt, we can say Small<Medium<Large<Extra Large. To apply label encoding on this previous example, the count of categories for the feature is made which is 4 different categories. The algorithm considers them at an order e.g. 0<1<2<3
Now let's try that out on our dataset!

In [114]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
df['Label_Encoded_Temp'] = LE.fit_transform(df.Temp)

In [115]:
df

        Temp   Color  Target  Label_Encoded_Temp
0        Hot     Red       1                   1
1       Cold    Blue       1                   0
2       Warm  Yellow       1                   4
3  Very Cold  Yellow       0                   2
4        Hot    Blue       0                   1
5       Cold     Red       1                   0
6   Very Hot    Blue       0                   3
7        Hot    Blue       0                   1
8       Warm  Yellow       1                   4
9        Hot     Red       0                   1

In the above example, total number of categories for temperature feature is 5 i.e 0,1,2,3,4. Each encoding is assigned to each category

ORDINAL ENCODING

Ordinal encoding is used to encode *ordinal* categorical variables too.

Ordinal Encoding makes use of the map function to map each category of features to a sequence of integers given(which is in a dictionary). The sequence of integers might be made as per order of data i.e Hot(1),Cold(2),Warm(3),Very Cold(4),Very Hot(5) or as per alphabetical order Cold(1),Hot(2),Very Cold(3),Very Hot(4), Warm(5). 

We could also classify based on temerature scale so we have Very Cold(1),Cold(2),Warm(3),Hot(4),Very Hot(5)

NB: Index starts at 1 in Ordinal Encoding unlike Label Encoding. Now let's try it out based on order of data as rendered by pandas

In [116]:
df = df.drop('Label_Encoded_Temp',axis=1)
res = {'Hot':1,'Cold':2,'Warm':3,'Very Cold':4,'Very Hot':5}
df['Ordinal_Encoded_Temp'] = df.Temp.map(res)

In [117]:
df

        Temp   Color  Target  Ordinal_Encoded_Temp
0        Hot     Red       1                     1
1       Cold    Blue       1                     2
2       Warm  Yellow       1                     3
3  Very Cold  Yellow       0                     4
4        Hot    Blue       0                     1
5       Cold     Red       1                     2
6   Very Hot    Blue       0                     5
7        Hot    Blue       0                     1
8       Warm  Yellow       1                     3
9        Hot     Red       0                     1

FREQUENCY ENCODING

Frequency encoding is used to encode *ordinal* categorical variables too. Frequency Encoding makes use of the frequency of the categories as labels

In [118]:
df = df.drop('Ordinal_Encoded_Temp',axis=1)
temp_size = df.groupby('Temp').size()
temp_freq = temp_size/len(df)
df.loc[:,'Freq_Encoded_Temp'] = df['Temp'].map(temp_freq)

In [119]:
df

        Temp   Color  Target  Freq_Encoded_Temp
0        Hot     Red       1                0.4
1       Cold    Blue       1                0.2
2       Warm  Yellow       1                0.2
3  Very Cold  Yellow       0                0.1
4        Hot    Blue       0                0.4
5       Cold     Red       1                0.2
6   Very Hot    Blue       0                0.1
7        Hot    Blue       0                0.4
8       Warm  Yellow       1                0.2
9        Hot     Red       0                0.4

ONE HOT ENCODING

This is used to encode *nominal* categorical variables i.e variables which can't be ordered. Each category of features is mapped to a vector that contains 1 and 0 denoting the abscence of the feature. Applying one hot encoding for the color

In [120]:
df = df.drop('Freq_Encoded_Temp',axis=1)
df1 = pd.get_dummies(df,columns=['Color'])

In [121]:
df1

        Temp  Target  Color_Blue  Color_Red  Color_Yellow
0        Hot       1           0          1             0
1       Cold       1           1          0             0
2       Warm       1           0          0             1
3  Very Cold       0           0          0             1
4        Hot       0           1          0             0
5       Cold       1           0          1             0
6   Very Hot       0           1          0             0
7        Hot       0           1          0             0
8       Warm       1           0          0             1
9        Hot       0           0          1             0

In [122]:
from sklearn.preprocessing import OneHotEncoder
ENC = OneHotEncoder()
sage = ENC.fit_transform(df.Color.values.reshape(-1,1)).toarray()
df2 = pd.DataFrame(sage,columns=['Color-'+str(ENC.categories_[0][i]) for i in range(len(ENC.categories_[0]))])
df3 = pd.concat([df,df2],axis=1)
df3

        Temp   Color  Target  Color-Blue  Color-Red  Color-Yellow
0        Hot     Red       1         0.0        1.0           0.0
1       Cold    Blue       1         1.0        0.0           0.0
2       Warm  Yellow       1         0.0        0.0           1.0
3  Very Cold  Yellow       0         0.0        0.0           1.0
4        Hot    Blue       0         1.0        0.0           0.0
5       Cold     Red       1         0.0        1.0           0.0
6   Very Hot    Blue       0         1.0        0.0           0.0
7        Hot    Blue       0         1.0        0.0           0.0
8       Warm  Yellow       1         0.0        0.0           1.0
9        Hot     Red       0         0.0        1.0           0.0

BINARY ENCODING

First each category of features are arranged based on order of data as rendered by pandas. So for example,in the temperature column we have Hot(1),Cold(2),Warm(3),Very Cold(4),Very Hot(5). 

Each sequence f integer is then converted to binary Hot(001),Cold(010),Warm(011),Very Cold(100),Very Hot(101). The digits of each binary number then form a seperate column.

In [123]:
import category_encoders as cenc
encoder = cenc.BinaryEncoder(cols=['Temp'])
df4 = encoder.fit_transform(df.Temp)
df = pd.concat([df,df4],axis=1)

In [124]:
df

        Temp   Color  Target  Temp_0  Temp_1  Temp_2  Temp_3
0        Hot     Red       1       0       0       0       1
1       Cold    Blue       1       0       0       1       0
2       Warm  Yellow       1       0       0       1       1
3  Very Cold  Yellow       0       0       1       0       0
4        Hot    Blue       0       0       0       0       1
5       Cold     Red       1       0       0       1       0
6   Very Hot    Blue       0       0       1       0       1
7        Hot    Blue       0       0       0       0       1
8       Warm  Yellow       1       0       0       1       1
9        Hot     Red       0       0       0       0       1